### PR TITLE
docs: add list of known reference implementations

### PR DESCRIPTION
**Pull request by tplooker**

### CODE REVIEW

**Comment by TallTed** [comment]
Just to be clear -- are these really [Reference Implementations](https://dbpedia.org/page/Reference_implementation) (can there be more than one?), or are they just Implementations for Reference?

**Comment by tplooker** [comment]
@TallTed fair point, would you be more amenable to language like 'Known Implementations'?

**Comment by tplooker** [comment]
Informational addition to the docs for the repo, addressed @TallTed's comments, merging

**Comment by TallTed** [comment]
It's likely worth changing the title of this PR, removing "reference" there as well

**Pull request merged**
